DDL1 = '''
create table gmv_test
            (id integer primary key autoincrement,
            order_code varchar(20) not null COMMENT '业务订单号',
            region text not null COMMENT '城市群' ,
            gmv numeric not null default 0 COMMENT '销售额',
            created_time timestamp not null COMMENT '创建时间',
            if_deleted boolean default 0 COMMENT '是否删除'
            )
'''

graph_schema = {
    "Node": {
        "label": "character",
        "name": "character_name"
        },
    "Relation": ['女友',
                 '男友',
                 '叔叔',
                 '侄女',
                 '上司',
                 '下属',
                 '孙女',
                 '祖母',
                 '祖父',
                 '姐姐',
                 '弟弟',
                 '队友',
                 '师傅',
                 '好友',
                 '恩师',
                 '儿子',
                 '丈夫',
                 '妻子',
                 '弟子',
                 '对手',
                 '同门',
                 '并称三忍',
                 '指导老师',
                 '想要的容器',
                 '母亲',
                 '弟媳',
                 '父亲',
                 '大伯子',
                 '哥哥',
                 '协助者',
                 '利用者',
                 '女儿',
                 '儿媳',
                 '婆婆',
                 '妹妹',
                 '堂妹',
                 '堂兄',
                 '老师',
                 '学生',
                 '夫妻',
                 '侄子',
                 '孙子',
                 '爷爷',
                 '徒弟',
                 '下一世',
                 '上一世',
                 '竞争对手',
                 '属下',
                 '队长',
                 '后辈',
                 '前辈',
                 '实验品',
                 '制造者',
                 '转世',
                 '前世',
                 '同伴',
                 '师弟',
                 '师兄',
                 '同伙',
                 '孩子',
                 '工具人',
                 '大哥',
                 '小弟',
                 '奶奶',
                 '救命恩人',
                 '被救者',
                 '晚辈']
    }
